# Generated by Django 4.2.27 on 2026-02-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercourseassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachercourseassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('level', 'group_name')},
        ),
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['teacher', 'classroom'], name='academics_t_teacher_1f9ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['classroom', 'course'], name='academics_t_classro_a76a63_idx'),
        ),
    ]
