# Generated by Django 4.2.27 on 2026-02-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_securityprofile_shift'),
        ('academics', '0002_initial'),
    ]

    operations = [
        # ─────────────────────────────────────────────
        # NEW MODELS
        # ─────────────────────────────────────────────
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={'ordering': ['order', 'label']},
        ),

        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[
                    (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'),
                    (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'),
                    (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December'),
                ])),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),

        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['code']},
        ),

        # ✅ IMPORTANT: on met period/level/room/created_by DIRECTEMENT ici,
        # sinon l'option ordering (period__year...) est risquée avant ajout des FK.
        migrations.CreateModel(
            name='MonthlyClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_monthly_groups',
                    to=settings.AUTH_USER_MODEL
                )),
                ('level', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='monthly_groups',
                    to='academics.academiclevel'
                )),
                ('period', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='class_groups',
                    to='academics.academicperiod'
                )),
                ('room', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='monthly_groups',
                    to='academics.room'
                )),
            ],
            options={
                'ordering': ['-period__year', '-period__month', 'level__order', 'group_name', 'room__code'],
            },
        ),

        migrations.CreateModel(
            name='StudentMonthlyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')],
                    default='pending',
                    max_length=12
                )),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='students',
                    to='academics.monthlyclassgroup'
                )),
                ('period', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='student_enrollments',
                    to='academics.academicperiod'
                )),
                ('student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='monthly_enrollments',
                    to='accounts.studentprofile'
                )),
            ],
        ),

        # ─────────────────────────────────────────────
        # ACADEMIC PERIOD constraints / index
        # ─────────────────────────────────────────────
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['year', 'month'], name='academics_a_year_e16cb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together={('year', 'month')},
        ),

        # ─────────────────────────────────────────────
        # ✅ FIX: AddField FIRST on TeacherCourseAssignment
        # ─────────────────────────────────────────────
        migrations.AddField(
            model_name='teachercourseassignment',
            name='monthly_group',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='teacher_assignments',
                to='academics.monthlyclassgroup'
            ),
        ),
        migrations.AddField(
            model_name='teachercourseassignment',
            name='period',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='teacher_assignments',
                to='academics.academicperiod'
            ),
        ),

        # ✅ THEN AddIndex (sinon crash)
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['period', 'teacher'], name='academics_t_period__a0bddc_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['period', 'monthly_group'], name='academics_t_period__496c7d_idx'),
        ),

        # ─────────────────────────────────────────────
        # ENROLLMENT indexes / unique
        # ─────────────────────────────────────────────
        migrations.AddIndex(
            model_name='studentmonthlyenrollment',
            index=models.Index(fields=['period', 'group'], name='academics_s_period__1af09f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmonthlyenrollment',
            index=models.Index(fields=['student', 'period'], name='academics_s_student_747a62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmonthlyenrollment',
            unique_together={('period', 'student')},
        ),

        # ─────────────────────────────────────────────
        # MonthlyClassGroup indexes / unique
        # ─────────────────────────────────────────────
        migrations.AddIndex(
            model_name='monthlyclassgroup',
            index=models.Index(fields=['period', 'level'], name='academics_m_period__6b8334_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyclassgroup',
            index=models.Index(fields=['period', 'room'], name='academics_m_period__efaed6_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyclassgroup',
            index=models.Index(fields=['level', 'group_name'], name='academics_m_level_i_2c7a62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyclassgroup',
            unique_together={('period', 'level', 'group_name', 'room')},
        ),
    ]
