# Generated by Django 4.2.27 on 2026-02-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academiclevel_academicperiod_monthlyclassgroup_room_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teachercourseassignment',
            name='academics_t_teacher_1f9ffc_idx',
        ),
        migrations.RemoveIndex(
            model_name='teachercourseassignment',
            name='academics_t_classro_a76a63_idx',
        ),
        migrations.RemoveIndex(
            model_name='teachercourseassignment',
            name='academics_t_period__a0bddc_idx',
        ),
        migrations.RemoveIndex(
            model_name='teachercourseassignment',
            name='academics_t_period__496c7d_idx',
        ),
        migrations.AlterField(
            model_name='monthlyclassgroup',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='academics.academicperiod'),
        ),
    ]
