# Generated by Django 4.2.27 on 2026-02-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_teachercourseassignment_academics_t_teacher_1f9ffc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyclassgroup',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='academics.academicperiod'),
        ),
    ]
