# Generated by Django 4.2.27 on 2026-02-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_monthlyclassgroup_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmonthlyenrollment',
            name='exam_unlock',
            field=models.BooleanField(default=False),
        ),
    ]
