# Generated by Django 4.2.27 on 2026-02-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentmonthlyenrollment_exam_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercourseassignment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercourseassignment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.room'),
        ),
    ]
