# Generated by Django 4.2.27 on 2026-02-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_teachercourseassignment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='academics.room'),
        ),
    ]
