# Generated by Django 4.2.27 on 2026-02-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_lat_alter_user_lng'),
        ('academics', '0008_alter_monthlygoal_classroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmonthlyenrollment',
            unique_together={('period', 'student', 'group')},
        ),
    ]
