# Generated by Django 4.2.27 on 2026-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_studentmonthlyenrollment_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['period', 'monthly_group'], name='academics_t_period__496c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['period', 'teacher'], name='academics_t_period__a0bddc_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['teacher', 'start_date'], name='academics_t_teacher_a7d3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['classroom', 'start_date'], name='academics_t_classro_0617bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachercourseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_titular', True)), fields=('period', 'monthly_group'), name='uniq_titular_per_group_per_period'),
        ),
    ]
