# Generated by Django 4.2.27 on 2026-02-18 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_teachercourseassignment_academics_t_period__496c7d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address_line1', models.CharField(blank=True, max_length=180, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=180, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('province', models.CharField(blank=True, max_length=80, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='South Africa', max_length=60, null=True)),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_m', models.PositiveIntegerField(default=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='academics.schoolcampus'),
        ),
    ]
