# Generated by Django 4.2.27 on 2026-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_schoolcampus_room_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyclassgroup',
            name='late_grace_min',
            field=models.PositiveSmallIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='monthlyclassgroup',
            name='start_time',
            field=models.TimeField(default='08:15'),
        ),
    ]
