# Generated by Django 4.2.27 on 2026-03-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_monthlyclassgroup_late_grace_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercourseassignment',
            name='is_speech_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='teachercourseassignment',
            index=models.Index(fields=['period', 'monthly_group', 'is_speech_teacher'], name='academics_t_period__2fb73b_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachercourseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_speech_teacher', True)), fields=('period', 'monthly_group'), name='uniq_speech_teacher_per_group_per_period'),
        ),
    ]
