# Generated by Django 4.2.27 on 2026-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_teachercourseassignment_is_speech_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.SmallIntegerField(default=0),
        ),
    ]
