# Generated by Django 4.2.27 on 2026-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_room_building_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyclassgroup',
            name='target_size',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
