# Generated by Django 4.2.27 on 2026-03-08 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_monthlyclassgroup_target_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmonthlyenrollment',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_students', to='academics.monthlyclassgroup'),
        ),
        migrations.AddIndex(
            model_name='studentmonthlyenrollment',
            index=models.Index(fields=['source_group'], name='academics_s_source__577e76_idx'),
        ),
    ]
