# Generated by Django 4.2.27 on 2026-02-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('class', 'Class'), ('exam', 'Exam'), ('festival', 'Festival')], default='class', max_length=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_payload', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='sessions_abc.classsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_in_session', models.CharField(choices=[('lead', 'Lead'), ('assistant', 'Assistant'), ('adjudicator', 'Adjudicator')], default='assistant', max_length=12)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='sessions_abc.classsession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.teacherprofile')),
            ],
            options={
                'unique_together': {('session', 'teacher')},
            },
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['classroom', 'date'], name='sessions_ab_classro_03fdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['date', 'session_type'], name='sessions_ab_date_ed7d16_idx'),
        ),
    ]
