# Generated by Django 4.2.27 on 2026-02-17 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_user_lat_alter_user_lng'),
        ('academics', '0009_alter_studentmonthlyenrollment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRoomCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=12)),
                ('scanned_by', models.CharField(choices=[('self_scan', 'Self scan'), ('teacher_scan', 'Teacher scan')], default='self_scan', max_length=12)),
                ('required_confirmations', models.PositiveSmallIntegerField(default=3)),
                ('monthly_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_checkins', to='academics.monthlyclassgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_checkins', to='academics.academicperiod')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_checkins', to='academics.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReenrollmentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('will_return', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reenroll_from', to='academics.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reenrollment_intents', to='accounts.studentprofile')),
                ('to_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reenroll_to', to='academics.academicperiod')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoomCheckInApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='attendance.dailyroomcheckin')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkin_approvals', to='accounts.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('left_early', 'Left early'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=12)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='academics.teachercourseassignment')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_attendance', to='accounts.teacherprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_attendance', to='academics.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_checkins', to='academics.monthlyclassgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='accounts.teacherprofile')),
            ],
            options={
                'unique_together': {('session', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudentExamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('monthly_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_entries', to='academics.monthlyclassgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_entries', to='academics.academicperiod')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_entries', to='academics.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_entries', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'date', 'monthly_group'], name='attendance__period__d5553a_idx'), models.Index(fields=['student', 'date'], name='attendance__student_e0b056_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentexamentry',
            constraint=models.UniqueConstraint(fields=('date', 'monthly_group', 'student', 'course_id'), name='uniq_exam_entry'),
        ),
        migrations.AddIndex(
            model_name='reenrollmentintent',
            index=models.Index(fields=['to_period', 'status'], name='attendance__to_peri_b099ce_idx'),
        ),
        migrations.AddIndex(
            model_name='reenrollmentintent',
            index=models.Index(fields=['student', 'to_period'], name='attendance__student_0496e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='reenrollmentintent',
            constraint=models.UniqueConstraint(fields=('student', 'to_period'), name='uniq_reenroll_intent_student_period'),
        ),
        migrations.AddIndex(
            model_name='dailyroomcheckinapproval',
            index=models.Index(fields=['checkin', 'approved'], name='attendance__checkin_45f3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyroomcheckinapproval',
            index=models.Index(fields=['teacher', 'decided_at'], name='attendance__teacher_0baeb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyroomcheckinapproval',
            constraint=models.UniqueConstraint(fields=('checkin', 'teacher'), name='uniq_checkin_teacher'),
        ),
        migrations.AddIndex(
            model_name='dailyroomcheckin',
            index=models.Index(fields=['period', 'date', 'room'], name='attendance__period__d9beda_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyroomcheckin',
            index=models.Index(fields=['monthly_group', 'date'], name='attendance__monthly_843fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyroomcheckin',
            index=models.Index(fields=['student', 'date'], name='attendance__student_0a80e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyroomcheckin',
            constraint=models.UniqueConstraint(fields=('date', 'room', 'student'), name='uniq_checkin_date_room_student'),
        ),
        migrations.AddIndex(
            model_name='courseattendance',
            index=models.Index(fields=['period', 'date'], name='attendance__period__da9f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='courseattendance',
            index=models.Index(fields=['assignment', 'date'], name='attendance__assignm_844d40_idx'),
        ),
        migrations.AddIndex(
            model_name='courseattendance',
            index=models.Index(fields=['student', 'date'], name='attendance__student_bbe7e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseattendance',
            unique_together={('date', 'assignment', 'student')},
        ),
    ]
