# Generated by Django 4.2.27 on 2026-02-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyroomcheckin',
            name='uniq_checkin_date_room_student',
        ),
        migrations.AddConstraint(
            model_name='dailyroomcheckin',
            constraint=models.UniqueConstraint(fields=('period', 'date', 'room', 'student'), name='uniq_checkin_period_date_room_student'),
        ),
    ]
