# Generated by Django 4.2.27 on 2026-02-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academiclevel_academicperiod_monthlyclassgroup_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_securityprofile_shift'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReenrollmentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('will_return', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reenroll_from', to='academics.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reenrollment_intents', to='accounts.studentprofile')),
                ('to_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reenroll_to', to='academics.academicperiod')),
            ],
            options={
                'indexes': [models.Index(fields=['to_period', 'status'], name='attendance__to_peri_b099ce_idx'), models.Index(fields=['student', 'to_period'], name='attendance__student_0496e3_idx')],
                'unique_together': {('student', 'to_period')},
            },
        ),
        migrations.CreateModel(
            name='DailyRoomCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_checkins', to='academics.academicperiod')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='academics.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_checkins', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'date', 'room'], name='attendance__period__d9beda_idx'), models.Index(fields=['student', 'date'], name='attendance__student_0a80e2_idx')],
                'unique_together': {('date', 'room', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('left_early', 'Left early'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=12)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='academics.teachercourseassignment')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_attendance', to='accounts.teacherprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_attendance', to='academics.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'date'], name='attendance__period__da9f9b_idx'), models.Index(fields=['assignment', 'date'], name='attendance__assignm_844d40_idx'), models.Index(fields=['student', 'date'], name='attendance__student_bbe7e0_idx')],
                'unique_together': {('date', 'assignment', 'student')},
            },
        ),
    ]
