# Generated by Django 4.2.27 on 2026-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_dailyroomcheckin_uniq_checkin_date_room_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroomcheckin',
            name='client_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyroomcheckin',
            name='client_tz_offset_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
