# Generated by Django 4.2.27 on 2026-03-05 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_teachercourseassignment_is_speech_teacher_and_more'),
        ('attendance', '0003_dailyroomcheckin_client_scanned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroomcheckin',
            name='client_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyroomcheckin',
            name='client_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyroomcheckin',
            name='distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyroomcheckin',
            name='geo_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyroomcheckin',
            name='scan_medium',
            field=models.CharField(choices=[('qr', 'QR'), ('nfc', 'NFC')], default='qr', max_length=8),
        ),
        migrations.AddField(
            model_name='dailyroomcheckin',
            name='scan_payload',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentexamentry',
            name='client_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentexamentry',
            name='client_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentexamentry',
            name='distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamentry',
            name='geo_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamentry',
            name='scan_medium',
            field=models.CharField(choices=[('qr', 'QR'), ('nfc', 'NFC')], default='qr', max_length=8),
        ),
        migrations.AddField(
            model_name='studentexamentry',
            name='scan_payload',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teachercheckin',
            name='client_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teachercheckin',
            name='client_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teachercheckin',
            name='distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercheckin',
            name='scan_medium',
            field=models.CharField(choices=[('qr', 'QR'), ('nfc', 'NFC')], default='qr', max_length=8),
        ),
        migrations.AddField(
            model_name='teachercheckin',
            name='scan_payload',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RoomScanTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('radius_m', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_tag', to='academics.room')),
            ],
        ),
    ]
