# Generated by Django 4.2.27 on 2026-03-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailyroomcheckin_client_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reenrollmentintent',
            name='execute_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reenrollmentintent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
