# Generated by Django 4.2.27 on 2026-02-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('person_type', models.CharField(choices=[('visitor', 'Visitor'), ('teacher', 'Teacher'), ('secretary', 'Secretary'), ('principal', 'Principal'), ('staff', 'Staff')], max_length=12)),
                ('purpose', models.CharField(choices=[('class', 'Class / Teaching'), ('meeting', 'Meeting'), ('administration', 'Administration'), ('speech_festival', 'Speech Festival'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=20)),
                ('purpose_detail', models.CharField(blank=True, max_length=255)),
                ('signature_base64', models.TextField(blank=True)),
                ('check_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_overstayed_notified', models.BooleanField(default=False)),
                ('overstayed_notified_at', models.DateTimeField(blank=True, null=True)),
                ('qr_payload', models.CharField(blank=True, max_length=255)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries_checked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['check_in_at'], name='gate_securi_check_i_927da0_idx'), models.Index(fields=['check_out_at'], name='gate_securi_check_o_925ff4_idx'), models.Index(fields=['person_type', 'check_in_at'], name='gate_securi_person__c9c9eb_idx'), models.Index(fields=['is_overstayed_notified', 'check_out_at'], name='gate_securi_is_over_e010a6_idx')],
            },
        ),
    ]
