# Generated by Django 4.2.27 on 2026-02-05 15:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Month must be in format YYYY-MM (e.g. 2026-02).', regex='^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('title', models.CharField(max_length=160)),
                ('raw_content', models.TextField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('corrected', 'Corrected'), ('coached', 'Coached'), ('shortlisted', 'Shortlisted'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SpeechPublicationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('publish', 'Publish'), ('reject', 'Reject')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('speech', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_decision', to='speeches.speech')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrected_content', models.TextField()),
                ('correction_notes', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('speech', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='speeches.speech')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_corrections', to='accounts.teacherprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechCoaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pronunciation_notes', models.TextField(blank=True)),
                ('coached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('speech', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coaching', to='speeches.speech')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_coachings', to='accounts.teacherprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comments', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjudicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_scores', to='accounts.teacherprofile')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='speeches.speech')),
            ],
            options={
                'unique_together': {('speech', 'adjudicator')},
            },
        ),
    ]
