# Generated by Django 4.2.27 on 2026-02-18 17:14

import apps.abc_apps.speeches.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_user_lat_alter_user_lng'),
        ('academics', '0012_monthlyclassgroup_late_grace_min_and_more'),
        ('speeches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('student_recording', 'Student recording'), ('teacher_coaching', 'Teacher coaching audio'), ('tts', 'Text to speech')], max_length=20)),
                ('audio_file', models.FileField(upload_to=apps.abc_apps.speeches.models.speech_audio_upload_path)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('engine', models.CharField(blank=True, max_length=40)),
                ('voice_name', models.CharField(blank=True, max_length=60)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('revised_content', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='SpeechShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(default='in_app', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechVisibilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='speechcorrection',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='speechcorrection',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='speechpublicationdecision',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='speechpublicationdecision',
            name='speech',
        ),
        migrations.AlterUniqueTogether(
            name='speechscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='speechscore',
            name='adjudicator',
        ),
        migrations.RemoveField(
            model_name='speechscore',
            name='speech',
        ),
        migrations.AlterUniqueTogether(
            name='speech',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='speechcoaching',
            name='coached_at',
        ),
        migrations.AddField(
            model_name='speech',
            name='author_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='speech',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.abc_apps.speeches.models.speech_cover_upload_path),
        ),
        migrations.AddField(
            model_name='speech',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speeches', to='academics.monthlyclassgroup'),
        ),
        migrations.AddField(
            model_name='speech',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speeches', to='academics.academicperiod'),
        ),
        migrations.AddField(
            model_name='speech',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speeches', to='academics.room'),
        ),
        migrations.AddField(
            model_name='speech',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='speech',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('class', 'Class'), ('school', 'School'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='speechcoaching',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speechcoaching',
            name='word_tips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='speech',
            name='month',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Month must be in format YYYY-MM (e.g. 2026-02).', regex='^\\d{4}-(0[1-9]|1[0-2])$')]),
        ),
        migrations.AlterField(
            model_name='speech',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_revision', 'Needs revision'), ('corrected', 'Corrected'), ('coached', 'Coached'), ('pending_approval', 'Pending approval'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='speech',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='speechcoaching',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachings', to='speeches.speech'),
        ),
        migrations.AddIndex(
            model_name='speech',
            index=models.Index(fields=['period', 'group', 'status'], name='speeches_sp_period__d3e660_idx'),
        ),
        migrations.AddIndex(
            model_name='speech',
            index=models.Index(fields=['status', 'created_at'], name='speeches_sp_status_4b5b0f_idx'),
        ),
        migrations.DeleteModel(
            name='SpeechCorrection',
        ),
        migrations.DeleteModel(
            name='SpeechPublicationDecision',
        ),
        migrations.DeleteModel(
            name='SpeechScore',
        ),
        migrations.AddField(
            model_name='speechvisibilitygrant',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_visibility_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechvisibilitygrant',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_grants', to='speeches.speech'),
        ),
        migrations.AddField(
            model_name='speechvisibilitygrant',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_visibility_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechshare',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='speeches.speech'),
        ),
        migrations.AddField(
            model_name='speechshare',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_shared_to_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechrevision',
            name='revised_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechrevision',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='speeches.speech'),
        ),
        migrations.AddField(
            model_name='speechlike',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='speeches.speech'),
        ),
        migrations.AddField(
            model_name='speechlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechcomment',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='speeches.speech'),
        ),
        migrations.AddField(
            model_name='speechcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechaudio',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='speeches.speech'),
        ),
        migrations.AddField(
            model_name='speechaudio',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechapproval',
            name='decided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechapproval',
            name='speech',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='speeches.speech'),
        ),
        migrations.AlterUniqueTogether(
            name='speechvisibilitygrant',
            unique_together={('speech', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='speechrevision',
            unique_together={('speech', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='speechlike',
            unique_together={('speech', 'user')},
        ),
        migrations.AddIndex(
            model_name='speechaudio',
            index=models.Index(fields=['speech', 'kind', 'created_at'], name='speeches_sp_speech__bf39e5_idx'),
        ),
    ]
