# Generated by Django 4.2.27 on 2026-02-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeches', '0002_speechapproval_speechaudio_speechcomment_speechlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('info', 'Info'), ('motivation', 'Motivation'), ('inspiration', 'Inspiration')], default='info', max_length=20),
        ),
        migrations.AddIndex(
            model_name='speech',
            index=models.Index(fields=['category', 'status'], name='speeches_sp_categor_2321ea_idx'),
        ),
        migrations.AddIndex(
            model_name='speech',
            index=models.Index(fields=['period', 'category'], name='speeches_sp_period__bf3cce_idx'),
        ),
    ]
