# Generated by Django 4.2.27 on 2026-02-05 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('university', 'University'), ('visa', 'Visa'), ('housing', 'Housing'), ('insurance', 'Insurance')], default='university', max_length=24)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('cover_webp', models.ImageField(blank=True, editable=False, null=True, upload_to='blog/covers_webp/')),
                ('cover_thumb_webp', models.ImageField(blank=True, editable=False, null=True, upload_to='blog/covers_thumb_webp/')),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_hash_fr', models.CharField(blank=True, default='', max_length=64)),
                ('source_hash_en', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-published_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=220)),
                ('excerpt', models.CharField(blank=True, default='', max_length=280)),
                ('content', models.TextField(blank=True, default='')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.post')),
            ],
            options={
                'verbose_name': 'post Translation',
                'db_table': 'blog_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['published', 'published_at'], name='blog_post_publish_ea558f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'published_at'], name='blog_post_categor_2281f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
