# Generated by Django 4.2.27 on 2026-01-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_hash_en',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='source_hash_fr',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
