# Generated by Django 4.2.27 on 2026-02-13 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_securityprofile_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'National ID Card'), ('driver_license', 'Driver License'), ('residence', 'Residence Permit')], max_length=20)),
                ('document_number', models.CharField(max_length=80)),
                ('country_of_issue', models.CharField(blank=True, default='', max_length=80)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(upload_to='verification/ids/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
