# Generated by Django 4.2.27 on 2026-02-05 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('qr', 'QR'), ('nfc', 'NFC'), ('manual', 'Manual')], max_length=10)),
                ('uid', models.CharField(max_length=120)),
                ('allowed', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('point_type', models.CharField(choices=[('gate', 'Gate'), ('room_door', 'Room Door'), ('inside_checkin', 'Inside Check-in')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('secretary', 'Secretary'), ('principal', 'Principal'), ('visitor', 'Visitor'), ('staff', 'Staff')], max_length=12)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('allow', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cred_type', models.CharField(choices=[('qr', 'QR'), ('nfc', 'NFC')], max_length=10)),
                ('uid', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('lost', 'Lost')], default='active', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
