# Generated by Django 4.2.27 on 2026-02-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_control', '0001_initial'),
        ('gate_security', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='access_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='access_control.accesspoint'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_points', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='access_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='access_control.accesspoint'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='visitor_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='gate_security.gateentry'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['uid', 'status'], name='access_cont_uid_797956_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accessrule',
            unique_together={('access_point', 'role')},
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['uid', 'scanned_at'], name='access_cont_uid_334718_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['allowed', 'scanned_at'], name='access_cont_allowed_a02cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_point', 'scanned_at'], name='access_cont_access__43a0fe_idx'),
        ),
    ]
