# Generated by Django 4.2.27 on 2026-02-14 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_user_lat_alter_user_lng'),
        ('academics', '0006_studentmonthlyenrollment_exam_unlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True, default='')),
                ('book_pages', models.CharField(blank=True, default='', max_length=120)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='academics.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='academics.monthlyclassgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='academics.academicperiod')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='accounts.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassGeneralRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('observation', models.TextField()),
                ('proposed_solutions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_remarks', to='academics.monthlyclassgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_remarks', to='academics.academicperiod')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_remarks', to='accounts.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTeachingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('monday', models.TextField(blank=True, default='')),
                ('tuesday', models.TextField(blank=True, default='')),
                ('wednesday', models.TextField(blank=True, default='')),
                ('thursday', models.TextField(blank=True, default='')),
                ('friday', models.TextField(blank=True, default='')),
                ('saturday', models.TextField(blank=True, default='')),
                ('sunday', models.TextField(blank=True, default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_plans', to='academics.course')),
                ('monthly_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='academics.monthlyclassgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='academics.academicperiod')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='accounts.teacherprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher', 'period'], name='app_teacher_teacher_32323e_idx'), models.Index(fields=['monthly_group', 'week_start'], name='app_teacher_monthly_84e873_idx')],
                'unique_together': {('teacher', 'monthly_group', 'course', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='StudentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('pronunciation', 'Pronunciation'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('fluency', 'Fluency'), ('listening', 'Listening'), ('writing', 'Writing'), ('behavior', 'Behavior'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('observation', models.TextField()),
                ('recommendation', models.TextField(blank=True, default='')),
                ('target_for_next', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_remarks', to='academics.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_remarks', to='academics.monthlyclassgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_remarks', to='academics.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student_remarks', related_query_name='teacher_student_remark', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student_remarks', to='accounts.teacherprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'period'], name='app_teacher_student_720f82_idx'), models.Index(fields=['group', 'period'], name='app_teacher_group_i_33ebec_idx'), models.Index(fields=['area'], name='app_teacher_area_da0fa9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProofScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('book_completed', 'Book completed'), ('exam_eligible', 'Exam eligible'), ('attendance_proof', 'Attendance proof'), ('other', 'Other')], max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proof_scans', to='academics.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_scans', to='academics.monthlyclassgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_scans', to='academics.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_scans', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_scans', to='accounts.teacherprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'group'], name='app_teacher_period__83a52a_idx'), models.Index(fields=['student', 'period'], name='app_teacher_student_a4c233_idx'), models.Index(fields=['teacher', 'period'], name='app_teacher_teacher_966368_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentMonthlyObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.JSONField(blank=True, default=dict)),
                ('teacher_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_objectives', to='academics.monthlyclassgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_objectives', to='academics.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_objectives', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_objectives', to='accounts.teacherprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'period'], name='app_teacher_student_7d595b_idx'), models.Index(fields=['group', 'period'], name='app_teacher_group_i_63a88f_idx')],
                'unique_together': {('period', 'group', 'student')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded')], default='submitted', max_length=12)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_comment', models.TextField(blank=True, default='')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app_teacher.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='app_teacher_student_3a2fe5_idx'), models.Index(fields=['homework'], name='app_teacher_homewor_d98de5_idx'), models.Index(fields=['status'], name='app_teacher_status_aa2693_idx')],
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['period', 'group'], name='app_teacher_period__56e9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['teacher', 'period'], name='app_teacher_teacher_d5714d_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['course', 'due_date'], name='app_teacher_course__073b73_idx'),
        ),
        migrations.AddIndex(
            model_name='classgeneralremark',
            index=models.Index(fields=['group', 'period'], name='app_teacher_group_i_0fd1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='classgeneralremark',
            index=models.Index(fields=['teacher', 'period'], name='app_teacher_teacher_7556e2_idx'),
        ),
    ]
