# Generated by Django 4.2.27 on 2026-02-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentproofscan',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('student', 'period', 'purpose', 'course'), name='uniq_proof_student_period_purpose_course'),
        ),
        migrations.AddConstraint(
            model_name='studentproofscan',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True)), fields=('student', 'period', 'purpose'), name='uniq_proof_student_period_purpose_nocourse'),
        ),
    ]
