# Generated by Django 4.2.27 on 2026-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0002_studentproofscan_uniq_proof_student_period_purpose_course_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentproofscan',
            name='uniq_proof_student_period_purpose_course',
        ),
        migrations.RemoveConstraint(
            model_name='studentproofscan',
            name='uniq_proof_student_period_purpose_nocourse',
        ),
        migrations.AddConstraint(
            model_name='studentproofscan',
            constraint=models.UniqueConstraint(fields=('period', 'student', 'course', 'purpose'), name='uniq_proofscan_period_student_course_purpose'),
        ),
    ]
